[package]
name = "zkpasslock"
version = "0.1.0"
authors = ["Your Name <mohamgoham@gmail.com>"]
edition = "2023"

[dependencies]
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
